"""F22 · Fe-Config consumer real-test against the production ``harness.api:app``.

Feature 22 is the Frontend consumer of IAPI-002 / IAPI-014 / IAPI-016 / IAPI-018
on five pages (SystemSettings / PromptsAndSkills / DocsAndROI / ProcessFiles /
CommitHistory).  This file pins the **schema contract** between the FE Zod
schemas (``apps/ui/src/lib/zod-schemas.ts``, generated by ``scripts/export_zod.py``
via ``datamodel-code-generator``) and the production pydantic models exposed
through the production ASGI app.

Why these are real tests:
    * Mounted on **production** ``harness.api:app`` (not a test factory) so any
      router-misregistration — exactly the F23 bug class — is caught before
      the FE green phase consumes them.
    * Real ``httpx.ASGITransport`` dispatch (NOT TestClient/respx) so the
      lifecycle of FastAPI dependency injection + production ``wire_services``
      runs end-to-end.
    * Real filesystem (``tmp_path``) for ``$HARNESS_HOME`` + git workdir
      (``subprocess git init``); no mocks for the system-under-real-test
      boundary.
    * Real keyring path uses a temporary ``KEYRING_FILE_PASSWORD`` + the
      ``keyrings.alt.file.PlaintextKeyring`` backend, mirroring IFR-006's
      production fallback.

Feature ref: feature 22

Traces To
=========
  F22-RT01  §IC useGeneralSettings + IAPI-002         GET /api/settings/general
            response carries the FE-required surface (api_key_ref OR
            api_key_masked are *exposed* fields; no plaintext)
            (FUNC/happy + NFR-008 SEC, real_http)

  F22-RT02  §IC useUpdateGeneralSettings + seq msg#3-5 PUT round-trip persists
            to ``$HARNESS_HOME/config.json`` and the response never echoes
            ``api_key_plaintext``.  (FUNC/happy + NFR-008 SEC, real_http +
            real_fs)

  F22-RT03  §IC useCommits + IFR-005 + §VRC NotAGitRepoBanner
            GET /api/git/commits against a non-git workdir returns a
            structured error the FE can map to ``code='not_a_git_repo'``.
            (FUNC/error, real_http + real_fs)

  F22-RT04  §IC useDiff + IFR-005 binary detection
            GET /api/git/diff/:sha against a real git repo with a binary
            commit yields a payload whose binary file carries
            ``kind='binary'`` (or an equivalent field FE can branch on).
            (FUNC/happy + BNDRY/binary-diff, real_http + real_fs)

  F22-RT05  §IC useValidate + IAPI-016 + FR-039
            POST /api/validate/:file with a deliberately invalid
            ``feature-list.json`` returns ``ok=false`` with a non-empty
            issues array — exact FE schema dependency.
            (FUNC/error + INTG/subprocess, real_http + real_fs)

  F22-RT06  §IC useSkillTree + IAPI-018 SEC
            GET /api/skills/tree with ``..`` path-traversal probe is rejected
            by the production routing layer (HTTP != 200), regardless of
            backend skill registry state.
            (SEC/path-traversal, real_http)
"""

from __future__ import annotations

import json
import os
import subprocess
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

import httpx
import pytest


pytestmark = [pytest.mark.real_http, pytest.mark.asyncio]


# ---------------------------------------------------------------------------
# Helpers (mirrored from test_f23_real_rest_routes.py for self-containment)
# ---------------------------------------------------------------------------
@contextmanager
def _env_override(**vars_: str) -> Iterator[None]:
    prev: dict[str, str | None] = {k: os.environ.get(k) for k in vars_}
    os.environ.update(vars_)
    try:
        yield
    finally:
        for k, v in prev.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


def _git_init(workdir: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=workdir, check=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.email=a@b",
            "-c",
            "user.name=A",
            "commit",
            "--allow-empty",
            "-q",
            "-m",
            "initial",
        ],
        cwd=workdir,
        check=True,
    )


def _git_commit_text_and_binary(workdir: Path) -> str:
    """Add a text file and a tiny PNG, commit, return SHA."""
    _git_init(workdir)
    (workdir / "README.md").write_text("hello\nworld\n", encoding="utf-8")
    # 8-byte PNG signature + 1-byte payload — git will detect as binary.
    (workdir / "logo.png").write_bytes(b"\x89PNG\r\n\x1a\n\x00")
    subprocess.run(["git", "add", "README.md", "logo.png"], cwd=workdir, check=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.email=a@b",
            "-c",
            "user.name=A",
            "commit",
            "-q",
            "-m",
            "feat: f22 fixture commit",
        ],
        cwd=workdir,
        check=True,
    )
    res = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=workdir,
        capture_output=True,
        text=True,
        check=True,
    )
    return res.stdout.strip()


def _client_for_app(app: Any) -> httpx.AsyncClient:
    transport = httpx.ASGITransport(app=app)
    return httpx.AsyncClient(transport=transport, base_url="http://testserver")


def _wire_app_for_test(app: Any, *, workdir: Path) -> None:
    """Production wiring helper.  In Red phase F22 consumer integration tests
    run AFTER F23 has shipped wire_services — if it is still missing, the
    ImportError surfaces here, which is the correct failure mode."""
    from harness.api import wire_services  # type: ignore[attr-defined]

    wire_services(app, workdir=workdir)


# ---------------------------------------------------------------------------
# F22-RT01 — GET /api/settings/general exposes the FE-consumed surface
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt01_get_settings_general_exposes_fe_surface(
    tmp_path: Path,
) -> None:
    """feature 22 RT01 FUNC/happy: production app GET /api/settings/general
    must return a payload that the FE Zod schema can parse.  The FE consumes
    ``api_key_ref`` (object with service+user) OR ``api_key_masked`` (string
    starting with '***').  ``keyring_backend`` ∈ {'native','keyrings.alt','fail'}.

    Red expectation: production ``GeneralSettings`` model is currently
    ``extra='allow'`` with only ``ui_density``; missing the F22-required fields
    → assertion fails → SUT must add them in Green.
    """
    from harness.api import app

    workdir = tmp_path / "workdir"
    workdir.mkdir()
    _git_init(workdir)
    home = tmp_path / "home"
    home.mkdir()
    with _env_override(HARNESS_HOME=str(home)):
        _wire_app_for_test(app, workdir=workdir)
        async with _client_for_app(app) as client:
            resp = await client.get("/api/settings/general")
    assert (
        resp.status_code == 200
    ), f"feature 22 RT01 expected 200; got {resp.status_code}: {resp.text!r}"
    body = resp.json()
    assert isinstance(body, dict), f"feature 22 RT01 expected JSON object; got {body!r}"
    # FE consumes at least one of these surface fields; both must be string-or-null
    has_keyring_backend = "keyring_backend" in body
    has_api_key_masked = "api_key_masked" in body
    has_api_key_ref = "api_key_ref" in body
    assert (
        has_keyring_backend
    ), f"feature 22 RT01 production /api/settings/general missing 'keyring_backend' (Red expected — Green must add)"
    assert (
        has_api_key_masked or has_api_key_ref
    ), f"feature 22 RT01 production /api/settings/general missing both 'api_key_masked' and 'api_key_ref' (Red expected — Green must add)"
    # NFR-008: never expose plaintext in GET response
    flat = json.dumps(body)
    assert (
        "api_key_plaintext" not in flat
    ), f"feature 22 RT01 NFR-008 violation: GET response leaks plaintext field name; body={body!r}"


# ---------------------------------------------------------------------------
# F22-RT02 — PUT /api/settings/general round-trip preserves no plaintext
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt02_put_settings_general_no_plaintext_in_response(
    tmp_path: Path,
) -> None:
    """feature 22 RT02 FUNC/happy + NFR-008: PUT with api_key_plaintext must
    persist via keyring and return a payload free of plaintext.  config.json
    on disk must NOT contain plaintext (NFR-008 measurement).
    """
    from harness.api import app

    workdir = tmp_path / "workdir"
    workdir.mkdir()
    _git_init(workdir)
    home = tmp_path / "home"
    home.mkdir()
    plaintext = "sk-rt02-secret-aabb"
    with _env_override(HARNESS_HOME=str(home)):
        _wire_app_for_test(app, workdir=workdir)
        async with _client_for_app(app) as client:
            resp = await client.put(
                "/api/settings/general",
                json={"api_key_plaintext": plaintext, "ui_density": "comfortable"},
            )
        assert (
            resp.status_code == 200
        ), f"feature 22 RT02 expected 200; got {resp.status_code}: {resp.text!r}"
        body = resp.json()
        flat = json.dumps(body)
        assert (
            plaintext not in flat
        ), f"feature 22 RT02 NFR-008 violation: PUT response echoes plaintext; body={body!r}"
        # Disk must not carry plaintext either
        cfg = home / "config.json"
        if cfg.exists():
            on_disk = cfg.read_text(encoding="utf-8")
            assert (
                plaintext not in on_disk
            ), f"feature 22 RT02 NFR-008 violation: config.json contains plaintext"


# ---------------------------------------------------------------------------
# F22-RT03 — GET /api/git/commits on non-git workdir → structured error
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt03_get_git_commits_non_git_returns_structured_error(
    tmp_path: Path,
) -> None:
    """feature 22 RT03 FUNC/error + IFR-005: non-git workdir must surface a
    structured error (code='not_a_git_repo' or equivalent string) the FE can
    map to NotAGitRepoBanner.
    """
    from harness.api import app

    workdir = tmp_path / "plain"
    workdir.mkdir()  # NOT git init
    _wire_app_for_test(app, workdir=workdir)
    async with _client_for_app(app) as client:
        resp = await client.get("/api/git/commits", params={"limit": 50})

    assert resp.status_code in (
        400,
        502,
    ), f"feature 22 RT03 expected 400/502; got {resp.status_code}: {resp.text!r}"
    body_text = resp.text.lower()
    assert (
        "not_a_git_repo" in body_text or "not a git" in body_text or "no_git" in body_text
    ), f"feature 22 RT03 expected structured error code; got body={resp.text!r}"


# ---------------------------------------------------------------------------
# F22-RT04 — GET /api/git/diff/:sha exposes binary-vs-text differentiation
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt04_get_git_diff_binary_marker(
    tmp_path: Path,
) -> None:
    """feature 22 RT04 BNDRY/binary-diff + IFR-005: real git repo with a
    binary file and a text file must yield a DiffPayload that flags the
    binary file via ``kind='binary'`` so the FE BinaryDiffPlaceholder branch
    can render without feeding empty hunks to react-diff-view.
    """
    from harness.api import app

    workdir = tmp_path / "repo"
    workdir.mkdir()
    sha = _git_commit_text_and_binary(workdir)
    _wire_app_for_test(app, workdir=workdir)
    async with _client_for_app(app) as client:
        resp = await client.get(f"/api/git/diff/{sha}")

    assert (
        resp.status_code == 200
    ), f"feature 22 RT04 expected 200; got {resp.status_code}: {resp.text!r}"
    body = resp.json()
    files = body.get("files") if isinstance(body, dict) else None
    assert (
        isinstance(files, list) and len(files) >= 2
    ), f"feature 22 RT04 expected ≥2 files in diff payload; got {body!r}"
    binary_files = [f for f in files if isinstance(f, dict) and f.get("kind") == "binary"]
    text_files = [f for f in files if isinstance(f, dict) and f.get("kind") == "text"]
    assert (
        len(binary_files) >= 1
    ), f"feature 22 RT04 expected ≥1 file with kind='binary'; got {files!r}"
    assert (
        len(text_files) >= 1
    ), f"feature 22 RT04 expected ≥1 file with kind='text'; got {files!r}"


# ---------------------------------------------------------------------------
# F22-RT05 — POST /api/validate/feature-list.json returns ok=false + issues[]
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt05_post_validate_returns_issues(
    tmp_path: Path,
) -> None:
    """feature 22 RT05 FUNC/error + INTG/subprocess + FR-039: POST a known-bad
    feature-list.json (empty features array fails the validator script's
    minimum-feature check) → ok=false + issues[] with at least one entry.
    The FE binds CrossFieldErrorList to the issues array.
    """
    from harness.api import app

    workdir = tmp_path / "repo"
    workdir.mkdir()
    _git_init(workdir)
    _wire_app_for_test(app, workdir=workdir)
    bad_payload = {
        "path": "feature-list.json",
        "content": json.dumps({"features": []}),
    }
    async with _client_for_app(app) as client:
        resp = await client.post(
            "/api/validate/feature-list.json", json=bad_payload
        )

    assert (
        resp.status_code == 200
    ), f"feature 22 RT05 expected 200 (validator non-fatal failures); got {resp.status_code}: {resp.text!r}"
    body = resp.json()
    assert isinstance(body, dict), f"feature 22 RT05 expected dict; got {body!r}"
    assert (
        body.get("ok") is False
    ), f"feature 22 RT05 expected ok=False for empty feature-list.json; got {body!r}"
    issues = body.get("issues")
    assert (
        isinstance(issues, list) and len(issues) >= 1
    ), f"feature 22 RT05 expected non-empty issues[]; got {body!r}"


# ---------------------------------------------------------------------------
# F22-RT06 — GET /api/skills/tree with .. probe is rejected
# ---------------------------------------------------------------------------
@pytest.mark.real_http
async def test_f22_feature_22_rt06_get_skills_tree_rejects_path_traversal(
    tmp_path: Path,
) -> None:
    """feature 22 RT06 SEC/path-traversal + FR-033 SEC: any '..' segment in a
    skills tree query must be rejected by the production app (4xx) so the FE
    relies on the rejection rather than client-side sanitisation alone.
    """
    from harness.api import app

    workdir = tmp_path / "repo"
    workdir.mkdir()
    _git_init(workdir)
    _wire_app_for_test(app, workdir=workdir)
    async with _client_for_app(app) as client:
        resp = await client.get(
            "/api/skills/tree", params={"path": "longtaskforagent/../../etc"}
        )

    assert (
        400 <= resp.status_code < 500
    ), f"feature 22 RT06 expected 4xx for '..' query; got {resp.status_code}: {resp.text!r}"
