/**
 * Icons — keyed re-export of lucide-react; preserves prototype Icons.jsx key names.
 * Default: stroke-width 1.75, size 16. Consumers may override via props.
 */
import * as React from "react";
import {
  Home as LuHome,
  Inbox as LuInbox,
  Zap as LuZap,
  FileText as LuFileText,
  Edit3 as LuEdit3,
  GitBranch as LuGitBranch,
  Book as LuBook,
  Settings as LuSettings,
  Search as LuSearch,
  ChevronRight as LuChevron,
  ChevronDown as LuChevronDown,
  ChevronUp as LuChevronUp,
  Check as LuCheck,
  CheckCircle as LuCheckCircle,
  X as LuX,
  Pause as LuPause,
  Play as LuPlay,
  AlertCircle as LuAlertCircle,
  AlertTriangle as LuAlertTriangle,
  HelpCircle as LuHelpCircle,
  Info as LuInfo,
  Loader as LuLoader,
  Plus as LuPlus,
  Folder as LuFolder,
  FolderOpen as LuFolderOpen,
  File as LuFile,
  Copy as LuCopy,
  ExternalLink as LuExternalLink,
  Eye as LuEye,
  EyeOff as LuEyeOff,
  Terminal as LuTerminal,
  Cpu as LuCpu,
  Clock as LuClock,
  DollarSign as LuDollarSign,
  GitCommit as LuGitCommit,
  GitPullRequest as LuGitPullRequest,
  RefreshCw as LuRefreshCw,
  Filter as LuFilter,
  MoreHorizontal as LuMoreH,
  Command as LuCommand,
  Download as LuDownload,
  Save as LuSave,
  Power as LuPower,
  type LucideProps,
} from "lucide-react";

type IconComp = (props: LucideProps) => React.ReactElement;

function wrap(Comp: React.ComponentType<LucideProps>): IconComp {
  const Wrapped: IconComp = (props) =>
    React.createElement(Comp, {
      size: 16,
      strokeWidth: 1.75,
      ...props,
    });
  return Wrapped;
}

export const Icons: Record<string, IconComp> = {
  Home: wrap(LuHome),
  Inbox: wrap(LuInbox),
  Zap: wrap(LuZap),
  FileText: wrap(LuFileText),
  Edit3: wrap(LuEdit3),
  GitBranch: wrap(LuGitBranch),
  Book: wrap(LuBook),
  Settings: wrap(LuSettings),
  Search: wrap(LuSearch),
  Chevron: wrap(LuChevron),
  ChevronDown: wrap(LuChevronDown),
  ChevronUp: wrap(LuChevronUp),
  Check: wrap(LuCheck),
  CheckCircle: wrap(LuCheckCircle),
  X: wrap(LuX),
  Pause: wrap(LuPause),
  Play: wrap(LuPlay),
  AlertCircle: wrap(LuAlertCircle),
  AlertTriangle: wrap(LuAlertTriangle),
  HelpCircle: wrap(LuHelpCircle),
  Info: wrap(LuInfo),
  Loader: wrap(LuLoader),
  Plus: wrap(LuPlus),
  Folder: wrap(LuFolder),
  FolderOpen: wrap(LuFolderOpen),
  File: wrap(LuFile),
  Copy: wrap(LuCopy),
  ExternalLink: wrap(LuExternalLink),
  Eye: wrap(LuEye),
  EyeOff: wrap(LuEyeOff),
  Terminal: wrap(LuTerminal),
  Cpu: wrap(LuCpu),
  Clock: wrap(LuClock),
  DollarSign: wrap(LuDollarSign),
  GitCommit: wrap(LuGitCommit),
  GitPullRequest: wrap(LuGitPullRequest),
  RefreshCw: wrap(LuRefreshCw),
  Filter: wrap(LuFilter),
  MoreH: wrap(LuMoreH),
  Command: wrap(LuCommand),
  Download: wrap(LuDownload),
  Save: wrap(LuSave),
  Power: wrap(LuPower),
};
