#!/usr/bin/env python3
"""
Initialize a long-task-agent project structure.

Creates the deterministic scaffold artifacts needed for multi-session agent work:
- feature-list.json (empty template with tech_stack, quality_gates, required_configs)
- task-progress.md (empty progress log)
- RELEASE_NOTES.md (living release notes, Keep a Changelog format)
- CLAUDE.md (appended with long-task-agent reference for cross-session continuity)
- examples/ directory with README.md (runnable examples for completed features)
- scripts/ directory (for validate_features.py, check_configs.py, check_devtools.py)
- docs/plans/ directory (for design docs and implementation plans)

NOTE: The following files are NOT generated by this script — they are created by the
LLM during the Initializer phase, tailored to the project's specific tech stack:
- long-task-guide.md (Worker session guide — LLM generates from SKILL.md + references)
- init.sh / init.ps1 (environment bootstrap — LLM generates from design doc)

Feature schema supports optional UI fields:
- "ui": true/false — marks features that require Chrome DevTools MCP functional testing
- "ui_entry": "/path" — entry URL for the UI feature (used by Worker for navigate_page)
- UI features must have at least one verification_step prefixed with "[devtools]"

Usage:
    python scripts/init_project.py <project-name> [--path <output-dir>]
           [--lang <language>] [--test-framework <framework>]
           [--coverage-tool <tool>]
           [--line-cov <0-100>] [--branch-cov <0-100>]
"""

import argparse
import json
import os
import shutil
import sys
from datetime import datetime


CLAUDE_MD_MARKER = "<!-- long-task-agent -->"


# B8 (feature #24) — pre-PyInstaller-integration guard against external
# plugin installers passing argparse flag names as positional arguments
# (project_name / --path). Without this guard, an installer that does
# `python init_project.py -- --version` would write a directory named
# "--version" into the repo root that PyInstaller --add-data later sweeps
# into the artefact. See feature design §Implementation Summary B8.
_RESERVED_FLAGS = {
    "--version", "--help", "--path", "-h", "--lang",
    "--test-framework", "--coverage-tool",
    "--line-cov", "--branch-cov",
}


def _validate_safe_arg(value, name):
    """Reject argparse-flag-shaped tokens used as positional arguments.

    Raises SystemExit(2) with a stderr diagnostic mentioning either
    'argparse flag' (dash-prefixed) or 'reserved' (whitelist match).
    No-ops on empty/None inputs (argparse handles required-presence).
    """
    if not isinstance(value, str) or value == "":
        return
    if value.startswith("-"):
        sys.stderr.write(
            f"error: {name} '{value}' looks like an argparse flag; refuse "
            f"to create directory\n"
        )
        sys.exit(2)
    if value in _RESERVED_FLAGS:
        sys.stderr.write(
            f"error: {name} '{value}' is a reserved argparse keyword; refuse "
            f"to create directory\n"
        )
        sys.exit(2)

_LONG_TASK_REFERENCE_BODY = (
    "\n\n<!-- long-task-agent -->\n"
    "## Long-Task Agent\n\n"
    "**语言规则（Language Rule）**：\n"
    "- 所有对用户的回复和生成的文档必须使用**简体中文**。\n"
    "- 以下内容保留英文原样，不翻译：代码标识符、函数/变量/字段名（如 `srs_trace`、`feature_id`）、命令行示例、工具名（`Skill` / `Agent` / `Grep` / `mvn test` 等）、YAML frontmatter 的 `name` / `description` 字段、commit message、文件路径。\n"
    "- 已成标识符的缩写保留英文：`SRS` / `FR` / `NFR` / `ATS` / `UCD` / `ST` / `TDD` / `UT` / `E2E`（首次出现可在括号内注中文）。\n"
    "- 术语统一参考 `docs/templates/glossary.md`（若存在），避免漂移。\n\n"
    "Multi-session workflow. `using-long-task` skill routes by project state:\n\n"
    "**Pre-init** (no `feature-list.json`):\n"
    "  requirements → ucd (if UI) → design → ats → init\n\n"
    "**Post-init** (has `feature-list.json`): route by root `current` lock:\n"
    "  - `current = {feature_id: N, phase: \"design\"}` → `long-task-work-design`\n"
    "  - `current = {feature_id: N, phase: \"tdd\"}`    → `long-task-work-tdd`\n"
    "  - `current = {feature_id: N, phase: \"st\"}`     → `long-task-work-st`\n"
    "  - `current = null` AND any feature `status=failing` → router picks next dep-ready feature\n"
    "  - `current = null` AND all features `status=passing` → `long-task-st` (system-wide)\n\n"
    "Override signals: `bugfix-request.json` or `increment-request.json` at project root\n"
    "→ `long-task-hotfix` / `long-task-increment` runs first (highest priority).\n\n"
    "One feature × one phase per session. Sessions terminate explicitly (no auto-loop).\n\n"
    "Quick status: `python scripts/count_pending.py feature-list.json`\n"
    "State source of truth: `feature-list.json`.\n"
    "<!-- /long-task-agent -->\n"
)

CLAUDE_MD_REFERENCE = _LONG_TASK_REFERENCE_BODY


def _append_agent_md_reference(out_dir: str, project_name: str, filename: str):
    """Append long-task-agent reference to an agent instruction file (idempotent)."""
    path = os.path.join(out_dir, filename)

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if CLAUDE_MD_MARKER in content:
            print(f"Skipped: {path} (reference already exists)")
            return
        with open(path, "a", encoding="utf-8") as f:
            f.write(_LONG_TASK_REFERENCE_BODY)
        print(f"Updated: {path} (appended long-task-agent reference)")
    else:
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# {project_name}\n")
            f.write(_LONG_TASK_REFERENCE_BODY)
        print(f"Created: {path}")


def append_claude_md_reference(out_dir: str, project_name: str):
    """Append long-task-agent reference to CLAUDE.md (idempotent)."""
    _append_agent_md_reference(out_dir, project_name, "CLAUDE.md")


def append_agents_md_reference(out_dir: str, project_name: str):
    """Append long-task-agent reference to AGENTS.md for opencode (idempotent)."""
    _append_agent_md_reference(out_dir, project_name, "AGENTS.md")



def create_feature_list(
    project_name: str,
    language: str = "TODO",
    test_framework: str = "TODO",
    coverage_tool: str = "TODO",
    line_coverage_min: int = 90,
    branch_coverage_min: int = 80,
) -> dict:
    return {
        "project": project_name,
        "created": datetime.now().strftime("%Y-%m-%d"),
        "tech_stack": {
            "language": language,
            "test_framework": test_framework,
            "coverage_tool": coverage_tool
        },
        "quality_gates": {
            "line_coverage_min": line_coverage_min,
            "branch_coverage_min": branch_coverage_min
        },
        "constraints": [],
        "assumptions": [],
        "required_configs": [],
        "features": []
    }


# Preset tool mappings per language
LANG_PRESETS = {
    "python": {
        "test_framework": "pytest",
        "coverage_tool": "pytest-cov",
    },
    "java": {
        "test_framework": "junit",
        "coverage_tool": "jacoco",
    },
    "javascript": {
        "test_framework": "jest",
        "coverage_tool": "c8-jest",
    },
    "typescript": {
        "test_framework": "vitest",
        "coverage_tool": "c8",
    },
    "c": {
        "test_framework": "ctest",
        "coverage_tool": "gcov",
    },
    "cpp": {
        "test_framework": "gtest",
        "coverage_tool": "gcov",
    },
    "c++": {
        "test_framework": "gtest",
        "coverage_tool": "gcov",
    },
    "go": {
        "test_framework": "go-test",
        "coverage_tool": "go-cover",
    },
}


def create_progress_log(project_name: str) -> str:
    return f"""# Task Progress — {project_name}

> Session log only. Current project state (which feature is locked, which
> phase it's in, how many features are passing) lives in
> `feature-list.json` — single source of truth. Query it with:
>
>     python scripts/count_pending.py feature-list.json

## Session Log

"""


def create_release_notes(project_name: str) -> str:
    return f"""# Release Notes — {project_name}

## [Unreleased]

### Added
- Initial project scaffold

### Changed
- (none yet)

### Fixed
- (none yet)

---

_Format: [Keep a Changelog](https://keepachangelog.com/) — Updated after every git commit._
"""


def create_examples_readme(project_name: str) -> str:
    return f"""# {project_name} — Examples

Usage examples for external developers and AI Code Agents. Generated after System Testing by the `long-task-finalize` skill.

## Prerequisites

*(Prerequisites will be listed when examples are generated.)*

## Examples

| # | Scenario | File | How to run |
|---|----------|------|------------|
| — | *(examples will be generated after System Testing)* | — | — |
"""



_KNOWN_OPTIONS = {
    "-h", "--help", "--path", "--lang",
    "--test-framework", "--coverage-tool",
    "--line-cov", "--branch-cov",
}


def _preflight_argv_guard(argv):
    """Inspect raw argv before argparse to surface a targeted diagnostic
    when a flag-shaped token is passed as the positional ``project_name``
    or as the value of ``--path``.

    Two separate scans:

    1. **Path value scan** — for ``--path <token>``, if ``token`` starts
       with ``-`` or is in :data:`_RESERVED_FLAGS`, refuse with an
       ``error: --path '...' looks like an argparse flag`` message.
    2. **Positional scan** — locate the first positional after stripping
       known options. If it begins with ``-`` or is in
       :data:`_RESERVED_FLAGS`, refuse with an ``error: project_name '...'
       looks like an argparse flag``. Special handling: when a single
       unknown flag-shaped token is the *only* positional candidate (e.g.,
       ``init_project.py --version``), treat it as the project_name to
       trigger the guard, since argparse would otherwise just print a
       generic ``missing required`` banner and the rogue ``--version/``
       directory risk remains plausible if a downstream caller wraps argv.

    Test Inventory B8-N1/N2/N3/P2 require stderr to contain "argparse
    flag" / "reserved" / "looks like" / "refuse".
    """
    args = list(argv)

    # 1) Path value scan
    for i, tok in enumerate(args):
        if tok == "--path" and i + 1 < len(args):
            nxt = args[i + 1]
            if nxt.startswith("-") or nxt in _RESERVED_FLAGS:
                sys.stderr.write(
                    f"error: --path '{nxt}' looks like an argparse flag; "
                    f"refuse to create directory\n"
                )
                sys.exit(2)

    # 2) Positional scan — find the first non-option token.
    idx = 0
    saw_double_dash = False
    positional_tok = None
    unknown_flag_tok = None
    while idx < len(args):
        tok = args[idx]
        if not saw_double_dash and tok == "--":
            saw_double_dash = True
            idx += 1
            continue
        if not saw_double_dash and tok.startswith("-"):
            if tok in _KNOWN_OPTIONS:
                value_taking = {
                    "--path", "--lang", "--test-framework",
                    "--coverage-tool", "--line-cov", "--branch-cov",
                }
                if tok in value_taking:
                    if idx + 1 < len(args):
                        idx += 2
                        continue
                    # Bare value-taking flag with no value supplied: the
                    # caller likely intended `--lang` as a project_name
                    # (B8-P2 reproducer). Surface guard message naming it
                    # as a reserved keyword.
                    unknown_flag_tok = tok
                    idx += 1
                    continue
                idx += 1
                continue
            # Unknown flag-shaped token — record it; argparse would later
            # reject, but we want our guard message first.
            unknown_flag_tok = tok
            idx += 1
            continue
        # First positional.
        positional_tok = tok
        break

    if positional_tok is None and unknown_flag_tok is not None:
        # Only an unknown flag was supplied — surface guard message
        # (test B8-N1/N2 reproducer: `init_project.py --version`).
        positional_tok = unknown_flag_tok

    if positional_tok is None:
        return  # let argparse handle "missing required"

    if positional_tok.startswith("-") or positional_tok in _RESERVED_FLAGS:
        kind = (
            "argparse flag" if positional_tok.startswith("-") and positional_tok not in _RESERVED_FLAGS
            else "reserved argparse keyword"
        )
        sys.stderr.write(
            f"error: project_name '{positional_tok}' looks like an {kind}; "
            f"refuse to create directory\n"
        )
        sys.exit(2)


def main():
    # B8 (feature #24) — pre-argparse guard. Without this, an external
    # plugin installer doing `init_project.py -- --version` produces a
    # rogue `--version/` directory in the repo root.
    _preflight_argv_guard(sys.argv[1:])

    parser = argparse.ArgumentParser(description="Initialize a long-task-agent project")
    parser.add_argument("project_name", help="Name of the project")
    parser.add_argument("--path", default=".", help="Output directory (default: current dir)")

    # Tech stack options
    parser.add_argument("--lang", default=None,
                        help="Project language (python/java/javascript/typescript/c/cpp). Auto-fills tool defaults.")
    parser.add_argument("--test-framework", default=None,
                        help="Test framework (e.g., pytest, junit, vitest, gtest)")
    parser.add_argument("--coverage-tool", default=None,
                        help="Coverage tool (e.g., pytest-cov, jacoco, c8, gcov)")

    # Quality gate thresholds
    parser.add_argument("--line-cov", type=int, default=90,
                        help="Min line coverage %% (default: 90)")
    parser.add_argument("--branch-cov", type=int, default=80,
                        help="Min branch coverage %% (default: 80)")

    args = parser.parse_args()

    # B8 (feature #24) — guard against external plugin installers passing
    # argparse flag names (e.g., "--version") or reserved keywords as
    # positional arguments. Reproducer: when an installer invokes
    # `python init_project.py -- --version`, argparse stops parsing at `--`
    # and accepts `--version` as `project_name`, which then becomes a
    # directory in the repo root (and gets collected by PyInstaller). The
    # guard rejects any value starting with `-` or matching a known reserved
    # CLI flag name.
    _validate_safe_arg(args.project_name, "project_name")
    _validate_safe_arg(args.path, "--path")

    out_dir = os.path.abspath(args.path)
    os.makedirs(out_dir, exist_ok=True)

    # Resolve tech stack from --lang preset, then override with explicit flags
    language = args.lang or "TODO"
    preset = LANG_PRESETS.get(language.lower(), {}) if language != "TODO" else {}
    test_framework = args.test_framework or preset.get("test_framework", "TODO")
    coverage_tool = args.coverage_tool or preset.get("coverage_tool", "TODO")

    # feature-list.json
    fl_path = os.path.join(out_dir, "feature-list.json")
    with open(fl_path, "w", encoding="utf-8") as f:
        json.dump(create_feature_list(
            args.project_name,
            language=language,
            test_framework=test_framework,
            coverage_tool=coverage_tool,
            line_coverage_min=args.line_cov,
            branch_coverage_min=args.branch_cov,
        ), f, indent=2, ensure_ascii=False)
    print(f"Created: {fl_path}")

    # CLAUDE.md (append reference, never overwrite)
    append_claude_md_reference(out_dir, args.project_name)

    # AGENTS.md (same reference for opencode, idempotent)
    append_agents_md_reference(out_dir, args.project_name)

    # task-progress.md
    tp_path = os.path.join(out_dir, "task-progress.md")
    with open(tp_path, "w", encoding="utf-8") as f:
        f.write(create_progress_log(args.project_name))
    print(f"Created: {tp_path}")

    # RELEASE_NOTES.md
    rn_path = os.path.join(out_dir, "RELEASE_NOTES.md")
    with open(rn_path, "w", encoding="utf-8") as f:
        f.write(create_release_notes(args.project_name))
    print(f"Created: {rn_path}")

    # scripts dir + copy helper scripts
    scripts_dir = os.path.join(out_dir, "scripts")
    os.makedirs(scripts_dir, exist_ok=True)

    # Resolve plugin root.
    # When this script runs from its original install location
    # (skills/long-task-init/scripts/), three levels up is the plugin root.
    # When the hook copies this script to a target project's scripts/ directory,
    # it also writes a `.long-task-plugin-root` hint file alongside it so the
    # copied script can locate the plugin's scripts/ directory correctly.
    _THIS_DIR = os.path.dirname(os.path.abspath(__file__))
    _hint_file = os.path.join(_THIS_DIR, '.long-task-plugin-root')
    if os.path.isfile(_hint_file):
        with open(_hint_file, encoding='utf-8') as _hf:
            _hint = _hf.read().strip()
        # Defensive: normalize Git Bash POSIX paths to Windows paths.
        # Git Bash writes /c/Users/... or c/Users/... (missing colon); Python on
        # Windows needs C:/Users/... for os.path.isdir() to succeed.
        if sys.platform == 'win32' and _hint:
            import re as _re
            _m = _re.match(r'^/?([a-zA-Z])/(.*)', _hint)
            if _m:
                _hint = _m.group(1).upper() + ':/' + _m.group(2)
        _PLUGIN_ROOT = _hint if (_hint and os.path.isdir(_hint)) else \
            os.path.dirname(os.path.dirname(os.path.dirname(_THIS_DIR)))
    else:
        _PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(_THIS_DIR)))
    plugin_scripts_dir = os.path.join(_PLUGIN_ROOT, "scripts")

    helper_scripts = [
        "validate_features.py",
        "check_devtools.py",
        "validate_guide.py",
        "get_tool_commands.py",
        "validate_st_cases.py",
        "validate_increment_request.py",
        "validate_bugfix_request.py",
        "check_st_readiness.py",
        "check_real_tests.py",
        "check_ats_coverage.py",
        "feature_paths.py",
        "count_pending.py",
        "migrate_sub_status.py",
        "auto_loop.py",
        "auto_loop_opencode.py",
    ]
    for script_name in helper_scripts:
        src = os.path.join(plugin_scripts_dir, script_name)
        dst = os.path.join(scripts_dir, script_name)
        if os.path.exists(src) and os.path.abspath(src) != os.path.abspath(dst):
            shutil.copy2(src, dst)
            print(f"Copied: {script_name} -> {scripts_dir}")
        elif not os.path.exists(src):
            print(f"Warning: {script_name} not found in {plugin_scripts_dir}")

    # docs/plans dir
    plans_dir = os.path.join(out_dir, "docs", "plans")
    os.makedirs(plans_dir, exist_ok=True)

    # docs/rules dir
    rules_dir = os.path.join(out_dir, "docs", "rules")
    os.makedirs(rules_dir, exist_ok=True)
    print(f"Created: {rules_dir}")

    # docs/test-cases dir
    test_cases_dir = os.path.join(out_dir, "docs", "test-cases")
    os.makedirs(test_cases_dir, exist_ok=True)
    print(f"Created: {test_cases_dir}")

    # docs/report dir
    report_dir = os.path.join(out_dir, "docs", "report")
    os.makedirs(report_dir, exist_ok=True)
    print(f"Created: {report_dir}")

    # docs/templates dir — copy ST case template
    templates_dir = os.path.join(out_dir, "docs", "templates")
    os.makedirs(templates_dir, exist_ok=True)
    plugin_templates_dir = os.path.join(_PLUGIN_ROOT, "docs", "templates")
    st_template_src = os.path.join(plugin_templates_dir, "st-case-template.md")
    st_template_dst = os.path.join(templates_dir, "st-case-template.md")
    if os.path.exists(st_template_src) and os.path.abspath(st_template_src) != os.path.abspath(st_template_dst):
        shutil.copy2(st_template_src, st_template_dst)
        print(f"Copied: st-case-template.md -> {templates_dir}")

    # examples dir + README.md
    examples_dir = os.path.join(out_dir, "examples")
    os.makedirs(examples_dir, exist_ok=True)
    examples_readme = os.path.join(examples_dir, "README.md")
    with open(examples_readme, "w", encoding="utf-8") as f:
        f.write(create_examples_readme(args.project_name))
    print(f"Created: {examples_readme}")

    print(f"\nProject '{args.project_name}' initialized at {out_dir}")
    print("Created: feature-list.json, CLAUDE.md, AGENTS.md, task-progress.md, RELEASE_NOTES.md, examples/, scripts/ (with helper scripts), docs/plans/, docs/test-cases/, docs/report/, docs/templates/")
    print("TODO (LLM generates during Initializer phase):")
    print("  - long-task-guide.md         (tailored Worker guide from SKILL.md + references + design doc)")
    print("  - init.sh / init.ps1         (environment bootstrap from design doc tech stack)")


if __name__ == "__main__":
    main()
